[package]
name = "generator_pwd"
version = "0.1.0"
authors = ["Lesieur Julien <lesieur.julien@orange.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
